language: python
python:
  - 2.7
  - 3.3
  - 3.4
install:
  - pip install ujson simplejson --use-mirrors
  - python setup.py install
script: nosetests tests
notifications:
  email:
    recipients:
      - marselester@ya.ru
    on_success: change
    on_failure: change
